/** @format */

export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const SIDEBAR_OPEN2 = "SIDEBAR_OPEN2";
export const SIDEBAR_CLOSE2 = "SIDEBAR_CLOSE2";
export const LANGUAGE_TOGGLE = "LANGUAGE_TOGGLE";
export const CHOSEN_LANGUAGE = "CHOSEN_LANGUAGE";
export const ADD_ROOM_TO_CART = "ADD_ROOM_TO_CART";
export const REMOVE_ROOM_ITEM = "REMOVE_ROOM_ITEM";
export const TOGGLE_ROOM_AMOUNT = "TOGGLE_ROOM_AMOUNT";
export const CLEAR_ROOM_CART = "CLEAR_ROOM_CART";
export const COUNT_ROOM_TOTALS = "COUNT_ROOM_TOTALS";
export const UPDATE_ROOM_DATES = "UPDATE_ROOM_DATES";
